export const getRequiredText = (text: string) => `${text} is required`;
export const getValidText = (text: string) => `${text} must be valid`;

const text = {
  EMAIL_VALID: "Enter a valid email",
  EMAIL_REQUIRED: "Email is required",
  PHONE_REQUIRED: "Phone is required",
  PHONE_VALID: "Enter a valid phone",
  NAME_REQUIRED: "Name is required",
  PASSWORD_REQUIRED: "Password is  required",
  Old_PASSWORD_REQUIRED: "Old Password is  required",
  PASSWORD_MATCH: "Both password needs to be same",
  FILE_REQUIRED: "File is required",
  FIRST_NAME_REQUIRED: "First Name is required",
  MIDDLE_NAME_REQUIRED: "Middle Name is required",
  LAST_NAME_REQUIRED: "Last Name is required",
  AGENCY_REQUIRED: "Agency Name is required",
  TOKEN_REQUIRED: "Please Enter 5 digit token",
  OTP_REQUIRED: "Please Enter 5 digit OTP",
  NEW_PASSWORD_REQUIRED: "New password is  required",
  CONFIRM_PASSWORD_REQUIRED: "Confirm Password is required field",
  PASSWORD_SUGGESTION:
    "Use 8 or more characters with letters, numbers & symbols",
  DESIGNATION_REQUIRED: "Designation is required",
  DEPARTMENT_REQUIRED: "Department is required",
  MENU_NAME_REQUIRED: "Menu name is required",
  URL_REQUIRED: "url is required",
  ICON_REQUIRED: "Icon is required",
  ROLE_REQUIRED: "Role is required",

  // * @ form
  YEAR_REQUIRED: "Year is required",
  QUARTER_REQUIRED: "Quarter is required",
  TYPE_OF_STATION_REQUIRED: "Type of station is required",
  PROVINCE_REQUIRED: "Province is required",
  DISTRICT_REQUIRED: "District is required",
  MUNICIPALITY_REQUIRED: "Municipality is required",
  WARD_REQUIRED: "Ward is required",
  VILLAGE_REQUIRED: "Village is required",
  LATITUDE_REQUIRED: "Latitude is required",
  LONGITUDE_REQUIRED: "Longitude is required",
  ELEVATION_REQUIRED: "Elevation is required",
  MEASURING_PARAMETER_REQUIRED: "Measuring parameter is required",
  LAND_OWNED_BY_REQUIRED: "Land owned by is required",
  PROJECT_SUPPORT_REQUIRED: "Project support is required",
  CO_FINANCING_LOCAL_REQUIRED: "Co-financing local is required",
  CO_FINANCING_PROVINCIAL_REQUIRED: "Co-financing provincial is required",
  CO_FINANCING_FEDERAL_REQUIRED: "Co-financing federal is required",
  RESOURCE_LEVERAGE_REQUIRED: "Resource leverage is required",
  REMARKS_REQUIRED: "Remarks is required",

  AFFILIATED_GROUP: "Affiliated is required",
  RENOVATION_TYPE: "Renovation is required",
  POND_CATEGORY: "Pond value is required",
  DIMENSION_AREA: "Dimension area is required",
  DIMENSION_DEPTH: "Dimension depth is required",
  POND_VOLUME: "Pond volume is required",
  POND_USE: "Pond usages is required",
  ESTIMATED_AREA_BY_CONVERSATION: "Estimation by conversation is required ",
  ESTIMATED_AREA_BY_IMMEDIATE: "Estimation by immediate is required ",
  BENEFITTED_HHS: "Benefitted by hhs is required",
  END_DATE_GREATER: "End Date must be greater than Start Date",
  START_DATE: "Start date is required",
  END_DATE: "End date is required",
  PROJECT_SUPPORT: "Project Support is required",
  CO_FINANCE_LOCAL: "Co-finance by local is required",
  CO_FINANCE_PROVINCIAL: "Co-finance by provincial is required",
  RESOURCES_LEVERAGE: "Resource Leverage is required",
  TOTAL: "Total Amount is required",
  INDICATOR_LINK: "Indicator link is required",
  REMARK: "Remarks is required",

  // attandance strings
  PARTICIPANT_NAME: "Name of the participant is required",
  POSITION: "Position is required",
  ORGANIZATION: "Organization is required",
  GROUP: "Select group/nrm/csos",
  SEX: "Please select gender",
  CASTE: "Please select cast",
  CONTACT: "Contact number id required",
  IS_YOUTH: "Select if person is youth",
  IS_DISABLED: "Select if person is disabled",
  SIGNATURE: "Please upload your signature",

  // workshop strings
  WATERSHED: "Watershed title is required",
  NAME_OF_EVENT: "Name of the event is required",
  EVENT_TYPE: "Event type is required",
  DATE: "Date is required",
  NO_OF_DAYS: "No of days is required",
  GENDER: "Gender is required",
  TOTAL_PEOPLE: "Total person is required",
  TOTAL_PEOPLE_IN_EVENT: "Total number of person in event is required",
  GOVERNMENT_FORM: "Government Form title is required",
  INGO_FORM: "Ingo Form Title is required",
  GROUP_FORM: "Group Form is required",
  OTHER_FORM: "Other Form is required",

  // nrm operational plan
  NAME_NRM_GROUP_REQUIRED: "Name of NRM Group is required",
  NRM_GROUP_TYPE_REQUIRED: "NRM Group Type is required",
  HANDOVER_DATE_REQUIRED: "Handover Date is required",
  RENEWAL_DATE_REQUIRED: "Renewal Date is required",
  RENEWAL_DATE_GREATER: "Renewal Date must be greater than Handover Date",

  CASTE_REQUIRED: "Caste is required",
  WELL_BEING_REQUIRED: "Well Being is required",


  // community water management system strings
  WATER_MANAGEMENT_SYSTEM_NAME: "Water management system is required",
  GROUPS_CBOS: "Affiliated NRM groups /cbos tittle is required",
  BENEFITED_POPULATION: "Benefited population is required",
  KEY_BENEFITS: "Key benefits title is required",
  RESOURCES_COMMUNITY: "Resources community title is required",

  SEARCH_REQUIRED: "Search text is required",

  // watershed strings
  NAME_OF_SUB_WATERSHED: "Name of sub watershed is required",
  AREA: "Area id required in ha.",
  KEY_CLIMATE_RISKS_AND_VULNERABILITIES:
    "Key climate and risks and vulnerabilities is required",
  STRUCTURAL_INTERVENTIONS: "Structural Interceptions is required",
  NON_STRUCTURAL_INTERVENTIONS: "Non-Structural Interceptions is required",
  EBA_WATERSHED_MANAGEMENT_OPTIONS:
    "Eba watershed management option is required",
  LANDUSE_POLICY_MEASURES: "Landuse Policy Measures is required",
  LONG_TERM_MONITORING_PLAN: "Long term monitoring plan is required",
  PROPOSED_KEY_INTERVENTAIONS: "Proposed key interventions is required",
  LINKAGES_WITH_MUICIPAL_MASTER_PLAN:
    "Linkages with muicipal master plan is required",
  INTERVENTIONS_TO_BE_SUPORTED_BY_PROJECT: "Interventions is required ",
  PREPARED_DATE: "Prepared date is required",
  PROJECT_STATUS: "Project status is required",
  IMPLEMENTATION_YEAR: "Implementation year is required",
  ENDORSED_BY: "Endorsed person is required",
  IMPLEMENTATION_STATUS: "Implementation status is required",
  INDICATOR_LINKED_WITH: "Person with indicator name is required",

  // contourTrenchSchema strings
  HORIZONTAL_DISTANCE_METER: "Horizontal distance is required",
  HILLSLOPE_DEGREE: "Hillslope degree is required",
  DIMENSION_WIDTH: "Dimension width is required",
  TOTAL_LENGTH_METER: "Total length in meter is required",
  CONTINEOUS_CONTOUR_TRENCH: "Continuous contour trench is required",
  STAGGERED_CONTOUR_TRENCH: "Staggered contour trench is required",
  BENEFITTED_HHS_TOTAL: "Total benefitted hhs is required ",
  BENEFITTED_POPULATION: "Benefitted population is required",
  BENEFITTED_POPULATION_TOTAL: "Total benefitted population is required",
  LAND_WITH_IMMEDIATE_BENEFITS: "Land with immediate benefits is required",
  PLANTATION_AT_THE_BREM: "Plantation at the brem is required",
  NAME_OF_SPECIES: "Name of the species is required",
  SAMPLE_OF_SEED: "Name of seed is required",
  COFINANCING_REQUIRED: "Co-financing required is required",
  PROJECT_REQUIRED: "Please select project with their permission",
};
export default text;
