export const getRequiredText = (text: string) => `${text} is required`;
export const getValidText = (text: string) => `${text} must be valid`;

const text = {
  EMAIL_VALID: "Enter a valid email",
  EMAIL_REQUIRED: "Email is required",
  PHONE_REQUIRED: "Phone is required",
  PHONE_VALID: "Enter a valid phone",
  NAME_REQUIRED: "Name is required",
  PASSWORD_REQUIRED: "Password is  required",
  Old_PASSWORD_REQUIRED: "Old Password is  required",
  PASSWORD_MATCH: "Both password needs to be same",
  FILE_REQUIRED: "File is required",
  FIRST_NAME_REQUIRED: "First Name is required",
  MIDDLE_NAME_REQUIRED: "Middle Name is required",
  LAST_NAME_REQUIRED: "Last Name is required",
  AGENCY_REQUIRED: "Agency Name is required",
  TOKEN_REQUIRED: "Please Enter 5 digit token",
  OTP_REQUIRED: "Please Enter 5 digit OTP",
  NEW_PASSWORD_REQUIRED: "New password is  required",
  CONFIRM_PASSWORD_REQUIRED: "Confirm Password is required field",
  PASSWORD_SUGGESTION:
    "Use 8 or more characters with letters, numbers & symbols",
  DESIGNATION_REQUIRED: "Designation is required",
  DEPARTMENT_REQUIRED: "Department is required",
  MENU_NAME_REQUIRED: "Menu name is required",
  URL_REQUIRED: "url is required",
  ICON_REQUIRED: "Icon is required",
  ROLE_REQUIRED: "Role is required",

  // * @ form
  YEAR_REQUIRED: "Year is required",
  QUARTER_REQUIRED: "Quarter is required",
  TYPE_OF_STATION_REQUIRED: "Type of station is required",
  PROVINCE_REQUIRED: "Province is required",
  DISTRICT_REQUIRED: "District is required",
  MUNICIPALITY_REQUIRED: "Municipality is required",
  WARD_REQUIRED: "Ward is required",
  VILLAGE_REQUIRED: "Village is required",
  LATITUDE_REQUIRED: "Latitude is required",
  LONGITUDE_REQUIRED: "Longitude is required",
  ELEVATION_REQUIRED: "Elevation is required",
  MEASURING_PARAMETER_REQUIRED: "Measuring parameter is required",
  LAND_OWNED_BY_REQUIRED: "Land owned by is required",
  PROJECT_SUPPORT_REQUIRED: "Project support is required",
  CO_FINANCING_LOCAL_REQUIRED: "Co-financing local is required",
  CO_FINANCING_PROVINCIAL_REQUIRED: "Co-financing provincial is required",
  CO_FINANCING_FEDERAL_REQUIRED: "Co-financing federal is required",
  RESOURCE_LEVERAGE_REQUIRED: "Resource leverage is required",
  REMARKS_REQUIRED: "Remarks is required",

  AFFILIATED_GROUP: "Affiliated is required",
  RENOVATION_TYPE: "Renovation is required",
};
export default text;
